authors:
  Cheung4843:
    name: Cheung4843
    description: Maintainer
    avatar: https://avatars.githubusercontent.com/u/46809977
    url: https://github.com/cheung4843
  Bloodnighttw:
    name: Bloodnighttw
    description: Contributor
    avatar: https://avatars.githubusercontent.com/u/44264182
    url: https://github.com/bloodnighttw